### ISSUE TITLE
Add debug option

### ISSUE THREAD

**Issue by azarouski** [zebrunner/mcloud-android-connector#3]
Add debug option like in `appium` repo:
https://github.com/zebrunner/appium/blob/develop/files/debug.sh

https://github.com/zebrunner/appium/blob/bc28c2ebb180968dff9a677c897275e346767eaf/Dockerfile#L68-L71

**Comment by azarouski** [comment]
fixed in #5

**Comment by dhreben** [comment]
Verified.
