### ISSUE TITLE
Research adb states and possibly how to call them manually

### ISSUE THREAD

**Issue by azarouski** [zebrunner/mcloud-android-connector#4]
- https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/adb.h;l=105-123
- https://android.stackexchange.com/questions/144770/what-represents-bootloader-in-the-possible-outputs-of-adb-get-state
- https://android.googlesource.com/platform/system/core/+/android-8.1.0_r9/adb/transport.cpp#737

**Comment by vdelendik** [comment]
@azarouski, please, inspect that adb states ported from appium correctly as part of heathcheck I believe...

**Comment by azarouski** [comment]
#6

**Comment by dhreben** [comment]
Verified.
